spring:
datasource:
driver-class-name: com.mysql.jdbc.Driver
url: jdbc:mysql://localhost:3306/erms_doc?UseUnicode=true&characterEncoding=utf-8&serverTimezone=UTC
username: root
password: '000000'
thymeleaf:
cache: false

mybatis:
mapper-locations: classpath:mappers/*.xml
type-aliases-package: com.xw.pojo
configuration:
log-impl: org.apache.ibatis.logging.stdout.StdOutImpl


server:
servlet:
context-path: /
port: 8001
pagehelper:
helper-dialect: mysql